Repository hmcts/sscs-hearings-api, pull requests merged in 2022-02, with the labels that each got.

#8 Sscs-10053 Adding Junit dependency
  build.gradle
Labels: ns:sscs, rel:sscs-hearings-api-pr-8, prd:sscs

#10 sscs-10118 Swagger API configuration
  .gitignore
  build.gradle
  config/owasp/suppressions.xml
  src/functionalTest/java/uk/gov/hmcts/reform/sscs/WelcomeTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/sscs/config/SwaggerPublisherTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/sscs/controllers/GetWelcomeTest.java
  src/main/java/uk/gov/hmcts/reform/sscs/HearingsApiApplication.java
  src/main/java/uk/gov/hmcts/reform/sscs/config/OpenAPIConfiguration.java
  src/main/java/uk/gov/hmcts/reform/sscs/controllers/RootController.java
  src/main/resources/application.yaml
Labels: ns:sscs, prd:sscs, rel:sscs-hearings-api-pr-10

#25 SSCS-10152 Temporarily disable mutation tests.
  Jenkinsfile_CNP
  Jenkinsfile_nightly
Labels: ns:sscs, prd:sscs, rel:sscs-hearings-api-pr-25
