Repository hmcts/sscs-hearings-api, pull requests merged in 2023-04, with the labels that each got.

#491 add suppressions
  config/owasp/suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-hearings-api-pr-491

#499 CVE-05.04.23
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-hearings-api-pr-499

#463 SSCS-11380-Added error log for HMC Service call
  src/main/java/uk/gov/hmcts/reform/sscs/service/exceptions/FeignClientErrorDecoder.java
  src/test/java/uk/gov/hmcts/reform/sscs/service/exceptions/FeignClientErrorDecoderTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-hearings-api-pr-463

#501 CVEFix-24.04.23
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-hearings-api-pr-501
