Repository hmcts/sscs-hearings-api, pull requests merged in 2024-07, with the labels that each got.

#620 Update suppression date
  config/owasp/suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-hearings-api-pr-620

#621 update sscs-common to 5.9.0
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-hearings-api-pr-621

#595 changed event when updating hearing
  src/main/java/uk/gov/hmcts/reform/sscs/helper/service/HearingsServiceHelper.java
  src/main/java/uk/gov/hmcts/reform/sscs/model/hmc/message/HearingUpdate.java
  src/main/java/uk/gov/hmcts/reform/sscs/model/hmc/reference/HmcStatus.java
  src/main/java/uk/gov/hmcts/reform/sscs/model/single/hearing/HearingSubChannel.java
  src/main/java/uk/gov/hmcts/reform/sscs/service/hmc/topic/HearingUpdateService.java
  src/main/java/uk/gov/hmcts/reform/sscs/service/hmc/topic/ProcessHmcMessageService.java
  src/test/java/uk/gov/hmcts/reform/sscs/helper/service/HearingsServiceHelperTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-hearings-api-pr-595
