Repository hmcts/sscs-hearings-api, pull requests merged in 2024-01, with the labels that each got.

#570 Empty commit
  README.md
Labels: ns:sscs, prd:sscs, rel:sscs-hearings-api-pr-570

#575 SSCSCI-529: Deployment filter
  charts/sscs-hearings-api/Chart.yaml
  charts/sscs-hearings-api/values.yaml
  src/main/java/uk/gov/hmcts/reform/sscs/jms/listener/HmcHearingsEventTopicListener.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/sscs/jms/listener/HmcHearingsEventTopicListenerTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-hearings-api-pr-575

#576 SSCSCI-529: Add deployment id
  src/main/resources/application.yaml
Labels: ns:sscs, prd:sscs, rel:sscs-hearings-api-pr-576
