Repository hmcts/sscs-hearings-api, pull requests merged in 2024-09, with the labels that each got.

#640 common version bump to update huddersfield/blackpool venues
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-hearings-api-pr-640

#644 SSCSSI-313 & SSCSSI-315: Fix broken trigger in Issue further evidence
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-hearings-api-pr-644

#643 SSCSCI-1028: use lang ref lookup logic from common
  build.gradle
  src/main/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsPartiesMapping.java
  src/main/java/uk/gov/hmcts/reform/sscs/helper/mapping/OverridesMapping.java
  src/main/java/uk/gov/hmcts/reform/sscs/service/ServiceHearingsService.java
  src/test/java/uk/gov/hmcts/reform/sscs/helper/mapping/OverridesMappingTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-hearings-api-pr-643
