Repository hmcts/sscs-hearings-api, pull requests merged in 2024-08, with the labels that each got.

#623 SSCSCI-957 dependency check bump
  build.gradle
  config/owasp/suppressions.xml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: ns:sscs, prd:sscs, rel:sscs-hearings-api-pr-623

#632 Sonarqube test coverage fix
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-hearings-api-pr-632

#603 Bump sscs-common version, change updateCaseV2 calls
  build.gradle
  config/pmd/ruleset.xml
  src/integrationTest/java/uk/gov/hmcts/reform/sscs/HearingsListenerTest.java
  src/integrationTest/resources/config/application_it_updateCaseV2.properties
  src/main/java/uk/gov/hmcts/reform/sscs/helper/mapping/HearingsDurationMapping.java
  src/main/java/uk/gov/hmcts/reform/sscs/helper/mapping/OverridesMapping.java
  src/main/java/uk/gov/hmcts/reform/sscs/service/HearingServiceConsumer.java
  src/main/java/uk/gov/hmcts/reform/sscs/service/HearingsService.java
  src/test/java/uk/gov/hmcts/reform/sscs/helper/mapping/OverridesMappingTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/service/HearingServiceConsumerTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/service/HearingsServiceRetryTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/service/HearingsServiceTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-hearings-api-pr-603, enable_keep_helm

#635 SSCSSI-225: upgraded commons
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-hearings-api-pr-635

#639 Update suppression date
  config/owasp/suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-hearings-api-pr-639
